#!/usr/bin/env python3
"""Build the 10-slide project deck (report/slides/ANLP_slides.pptx).

All numbers come from runs/run4_full_clean_2026-05-04/results/metrics.csv,
runs/run3_led_finetuned_2026-05-03/kernel.log and runs/reeval_valid.txt.
Figures are generated by make_led_curve.py and make_leaderboard_chart.py.
"""
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

NAVY = RGBColor(0x0A, 0x3D, 0x7A)
DARK = RGBColor(0x22, 0x22, 0x22)
GREY = RGBColor(0x66, 0x66, 0x66)
RED = RGBColor(0xB0, 0x00, 0x00)
LIGHT = RGBColor(0xF2, 0xF5, 0xFA)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)

SW, SH = Inches(13.333), Inches(7.5)

prs = Presentation()
prs.slide_width, prs.slide_height = SW, SH
BLANK = prs.slide_layouts[6]


def add_slide():
    return prs.slides.add_slide(BLANK)


def textbox(slide, x, y, w, h):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    return tf


def set_run(r, text, size, color=DARK, bold=False, italic=False, font="Calibri"):
    r.text = text
    r.font.size = Pt(size)
    r.font.color.rgb = color
    r.font.bold = bold
    r.font.italic = italic
    r.font.name = font


def title_bar(slide, text, kicker=None):
    bar = slide.shapes.add_shape(1, 0, 0, SW, Inches(1.1))  # 1 = rectangle
    bar.fill.solid()
    bar.fill.fore_color.rgb = NAVY
    bar.line.fill.background()
    tf = bar.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.55)
    tf.margin_top = Inches(0.12)
    p = tf.paragraphs[0]
    set_run(p.add_run(), text, 27, WHITE, bold=True)
    if kicker:
        p2 = tf.add_paragraph()
        set_run(p2.add_run(), kicker, 13, RGBColor(0xC9, 0xD8, 0xEC))


def bullets(slide, items, x=Inches(0.6), y=Inches(1.45), w=Inches(12.1),
            h=Inches(5.6), size=17):
    tf = textbox(slide, x, y, w, h)
    first = True
    for item in items:
        if isinstance(item, str):
            item = [(item, {})]
        level = item[0][1].pop("level", 0) if item else 0
        p = tf.paragraphs[0] if first else tf.add_paragraph()
        first = False
        p.level = level
        p.space_after = Pt(8)
        for text, kw in item:
            sz = kw.pop("size", size - 2 * level)
            set_run(p.add_run(), text, sz, **kw)
    return tf


def footer(slide, n):
    tf = textbox(slide, SW - Inches(1.0), SH - Inches(0.42), Inches(0.8), Inches(0.3))
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.RIGHT
    set_run(p.add_run(), str(n), 11, GREY)


def quote_box(slide, x, y, w, h, label, text, label_color=NAVY):
    box = slide.shapes.add_shape(1, x, y, w, h)
    box.fill.solid()
    box.fill.fore_color.rgb = LIGHT
    box.line.color.rgb = RGBColor(0xC5, 0xD0, 0xE0)
    box.line.width = Pt(0.75)
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.18)
    tf.margin_right = Inches(0.18)
    tf.margin_top = Inches(0.1)
    p = tf.paragraphs[0]
    set_run(p.add_run(), label, 13, label_color, bold=True)
    p2 = tf.add_paragraph()
    set_run(p2.add_run(), text, 13, DARK, italic=True)


# ---------------------------------------------------------------- 1 · Title
s = add_slide()
tf = textbox(s, Inches(0.9), Inches(2.1), Inches(11.5), Inches(2.2))
p = tf.paragraphs[0]
set_run(p.add_run(), "Summarising Football Match Commentaries", 36, NAVY, bold=True)
p = tf.add_paragraph()
set_run(p.add_run(),
        "A Comparative Study of Prompting and Fine-tuning on Long-form Sports Audio Transcripts",
        20, DARK)
tf = textbox(s, Inches(0.9), Inches(4.6), Inches(11.5), Inches(1.6))
p = tf.paragraphs[0]
set_run(p.add_run(), "Marco Panciera  ·  Christian Dalfarra", 18, DARK, bold=True)
p = tf.add_paragraph()
set_run(p.add_run(), "Applied Natural Language Processing — University of Trento — May 2026",
        14, GREY)

# ------------------------------------------------- 2 · Problem & questions
s = add_slide()
title_bar(s, "The task: 2.5 hours of radio → 300-word match report")
bullets(s, [
    [("Input: ", {"bold": True}),
     ("Whisper transcript of live BBC Radio 5 commentary — median ~25,000 words, "
      "noisy, fragmented, full of irrelevant detail.", {})],
    [("Output: ", {"bold": True}),
     ("a structured match report (~300 words): score line, key events, short tactical note.", {})],
    [("Why it is hard: ", {"bold": True}),
     ("inputs exceed every standard transformer context window (1,024 tokens ≈ 4% of a match); "
      "references for training are scarce.", {})],
    "",
    [("Two empirically answerable questions:", {"bold": True, "color": NAVY})],
    [("1.  Chunk-and-aggregate, or a long-context encoder (LED-16384)?", {"level": 1})],
    [("2.  For each input strategy — prompting a general model, or fine-tuning on small in-domain data?",
      {"level": 1})],
], size=18)
footer(s, 2)

# ------------------------------------------------------------- 3 · Dataset
s = add_slide()
title_bar(s, "A custom dataset: 99 matches, 43 years, 12 competitions",
          "BBC radio audio  →  Whisper transcription  →  GPT-4 reference summaries")
bullets(s, [
    [("Audio: ", {"bold": True}),
     ("BBC Radio 5 Live archive (YouTube, via yt-dlp) — ~19 GB MP3, matches from 1983 to 2026.", {})],
    [("Transcription: ", {"bold": True}),
     ("Whisper-small; full transcript + time-aligned segments with pitch/energy prosodic features.", {})],
    [("References: ", {"bold": True}),
     ("GPT-4 (ChatGPT web, search enabled) prompted per match identifier; facts grounded in "
      "web-retrieved match reports, BBC sourcing verified for every match; fixed template, ~300 words. "
      "A pragmatic, disclosed compromise — no human summaries exist for radio commentary.", {})],
    [("Split: ", {"bold": True}),
     ("80 train / 10 val / 9 test, stratified, committed to the repo for reproducibility.", {})],
    "",
    [("Known noise floor: ", {"bold": True, "color": RED}),
     ("Whisper systematically corrupts player names (“Bergkamp” → “Burgkamp”) — "
      "an irreducible ceiling on surface-overlap metrics.", {})],
], size=18)
footer(s, 3)

# -------------------------------------------------- 4 · Experimental design
s = add_slide()
title_bar(s, "Design: 2 input pipelines × 2 learning paradigms",
          "3 architectures · 3 prompt styles · 11 evaluated conditions")
rows = [
    ["", "Chunk + aggregate", "Long-context (16,384 tokens)"],
    ["Prompting\n(zero / few / CoT)", "FLAN-T5-Large (512)\nBART-Large-CNN (1,024)", "LED-base-16384"],
    ["Fine-tuning", "BART as the merge step\n(“chunk-merger” recipe)", "LED on 8,192-token\nrandom windows"],
]
tbl = s.shapes.add_table(3, 3, Inches(0.8), Inches(1.6), Inches(11.7), Inches(3.1)).table
tbl.columns[0].width = Inches(2.9)
tbl.columns[1].width = Inches(4.4)
tbl.columns[2].width = Inches(4.4)
for i, row in enumerate(rows):
    for j, cell_text in enumerate(row):
        cell = tbl.cell(i, j)
        cell.fill.solid()
        cell.fill.fore_color.rgb = NAVY if (i == 0 or j == 0) else WHITE
        tfc = cell.text_frame
        tfc.word_wrap = True
        for k, line in enumerate(cell_text.split("\n")):
            p = tfc.paragraphs[0] if k == 0 else tfc.add_paragraph()
            hdr = i == 0 or j == 0
            set_run(p.add_run(), line, 15 if hdr else 14,
                    WHITE if hdr else DARK, bold=hdr)
bullets(s, [
    [("Chunk + aggregate: ", {"bold": True}),
     ("segment-aligned chunks with 1-segment overlap → per-chunk summary → merge → BoW-cosine dedup.", {})],
    [("Long-context: ", {"bold": True}),
     ("whole transcript in one LED forward pass; global attention on BOS; gradient checkpointing on a T4.", {})],
    [("All experiments on free-tier Kaggle (1× T4, 15.6 GB); seeds fixed; every prediction saved to disk.", {})],
], y=Inches(5.0), size=16)
footer(s, 4)

# ------------------------------------------------------------- 5 · Results
s = add_slide()
title_bar(s, "Results: fine-tuning wins by a wide margin",
          "Test ROUGE-L, clean 9-match test set (run 4)")
s.shapes.add_picture("figures/leaderboard.png", Inches(1.1), Inches(1.45), width=Inches(11.1))
tf = textbox(s, Inches(0.7), Inches(6.75), Inches(12.0), Inches(0.6))
p = tf.paragraphs[0]
set_run(p.add_run(),
        "* Fine-tuned LED trained before the dataset fix; scored on the 5 valid-reference test matches "
        "— close, but not strictly comparable to the 9-match protocol of the other rows.",
        12, GREY, italic=True)
footer(s, 5)

# ----------------------------------------- 6 · Finding 1: chunk-merger
s = add_slide()
title_bar(s, "Finding 1 — Match the training distribution, not the context window",
          "The “chunk-merger” fine-tuning recipe")
bullets(s, [
    [("Naive fine-tuning ", {"bold": True}),
     ("on (transcript[:1024] → gold) shows BART only the first ~5 minutes of a 2.5-hour match.", {})],
    [("Chunk-merger recipe: ", {"bold": True, "color": NAVY}),
     ("run pre-trained BART on every chunk → concatenate the ~30 mini-summaries (~960 tokens) → "
      "fine-tune BART to map that intermediate to the gold report. "
      "Training input now matches what the model sees at inference.", {})],
    [("Two-phase schedule: ", {"bold": True}),
     ("encoder frozen 3 epochs, then unfrozen; early stopping on val ROUGE-L.", {})],
    "",
    [("Same model, same pipeline, same test set:", {"bold": True})],
    [("pre-trained BART 0.147   →   fine-tuned BART 0.248  ( +69% relative )",
      {"size": 22, "bold": True, "color": NAVY, "level": 1})],
    [("+55% over the strongest prompting condition of any architecture (LED few-shot, 0.160).",
      {"level": 1})],
], size=18)
footer(s, 6)

# ---------------------------------- 7 · Finding 2: ranking inversion
s = add_slide()
title_bar(s, "Finding 2 — Long context wins at prompting, loses at fine-tuning")
bullets(s, [
    [("Prompting: ", {"bold": True}),
     ("LED long-context (avg 0.158) beats BART chunk (0.124) and FLAN chunk (0.058) — "
      "the 16k window preserves cross-segment information that chunking discards.", {})],
    [("Fine-tuning: ", {"bold": True}),
     ("the ranking inverts — BART chunk-merger 0.248 vs fine-tuned LED 0.219.", {})],
    "",
    [("Why: sample efficiency at N = 80.", {"bold": True, "color": NAVY})],
    [("BART learns from a ~960-token pre-distilled intermediate whose features are already informative.",
      {"level": 1})],
    [("LED must learn what matters inside raw 8,192-token windows from scratch — "
      "too few pairs to learn long-range attention patterns.", {"level": 1})],
    "",
    [("Secondary finding: ", {"bold": True}),
     ("zero-shot beats few-shot and CoT in every model family — examples eat the input budget in "
      "chunked pipelines, and LED-base is not instruction-tuned, so prompt style barely matters.", {})],
], size=18)
footer(s, 7)

# --------------------------------------- 8 · Finding 3: hallucination
s = add_slide()
title_bar(s, "Finding 3 — Models learn the format, not the facts",
          "Test match: 2001 FA Cup Final — true result: Liverpool 2–1 Arsenal, Millennium Stadium")
quote_box(s, Inches(0.6), Inches(1.6), Inches(6.0), Inches(2.2),
          "Fine-tuned BART (best model)",
          "“Liverpool 1–1 Arsenal (Liverpool win 2–3 on penalties) 20 May 2014 — "
          "Emirates Stadium, London. The match was contested … in the 2014 FA Cup Final…”")
quote_box(s, Inches(6.85), Inches(1.6), Inches(6.0), Inches(2.2),
          "Fine-tuned LED",
          "“Liverpool 1–0 Arsenal, Premier League, 20 May 2001 — Anfield, Anfield, "
          "Emirates Stadium, Anfield… Liverpool dominated the first half…”")
bullets(s, [
    [("Perfect surface form — score line, date line, report prose — with the year, stadium, "
      "competition and result all invented.", {"bold": True})],
    [("ROUGE rewards it anyway: ", {"bold": True, "color": RED}),
     ("the n-grams that overlap with the reference (team names, date formats, “in the Xth minute”) "
      "are exactly what the models do reproduce; hallucinated facts cost nothing.", {})],
    [("Prompted baselines fail differently: FLAN emits template fragments; "
      "LED continues the commentary instead of summarising it.", {})],
], y=Inches(4.15), size=17)
footer(s, 8)

# ------------------------------ 9 · Data-quality incident + LED curve
s = add_slide()
title_bar(s, "The biggest improvement was not a model change",
          "Five silent LED training failures + one dataset bug")
bullets(s, [
    [("33% of training references were 0-byte files ", {"bold": True, "color": RED}),
     ("(and 44% of test references) — silently teaching models to emit empty strings and "
      "deflating every score ~1.8×.", {})],
    [("Predicted correction ratio matched the measured one almost exactly "
      "(e.g. fine-tuned BART 0.136 → 0.248 after the fix).", {})],
    [("LED also needed 5 bug fixes ", {"bold": True}),
     ("(defeated random-window sampler, collapse-to-EOS, decoder sentinel overflow, "
      "lost checkpoint, CLI truncation).", {})],
    [("After the fixes: a clean, monotone training curve → the earlier collapses were "
      "data and code defects, not modelling limits.", {"bold": True, "color": NAVY})],
], x=Inches(0.6), y=Inches(1.45), w=Inches(6.3), size=16)
s.shapes.add_picture("figures/led_training_curve.png", Inches(7.15), Inches(1.9), width=Inches(5.7))
tf = textbox(s, Inches(7.15), Inches(5.65), Inches(5.7), Inches(0.5))
p = tf.paragraphs[0]
set_run(p.add_run(), "LED fine-tuning after the fixes: val ROUGE-L peaks at 0.172 (epoch 9).",
        12, GREY, italic=True)
footer(s, 9)

# ---------------------------------------------- 10 · Conclusions
s = add_slide()
title_bar(s, "Conclusions & limitations")
bullets(s, [
    [("1.  Fine-tuning a distribution-matched chunk pipeline is the best recipe at small N ", {"bold": True}),
     ("— +69% over the same pre-trained model, +55% over the best prompting baseline.", {})],
    [("2.  Context length is not a substitute for supervision ", {"bold": True}),
     ("— long-context wins only when no fine-tuning is possible.", {})],
    [("3.  Surface metrics cannot see the failure that matters ", {"bold": True}),
     ("— fluent, confidently wrong match reports score well on ROUGE. "
      "Faithfulness evaluation is the natural next step.", {})],
    "",
    [("Limitations we state openly:", {"bold": True, "color": RED})],
    [("Search-grounded GPT-4 references → facts anchored in web reports, but still ungrounded in the "
      "transcript, stylistically homogeneous, and not exactly reproducible (search results drift).",
      {"level": 1})],
    [("n = 9 test matches → differences within ±0.02 ROUGE-L are noise; no significance testing.",
      {"level": 1})],
    [("N = 80 training pairs → both fine-tuned models overfit (val 0.31 → test 0.25 for BART).",
      {"level": 1})],
    [("Fine-tuned LED not re-trained after the dataset fix → its 0.219 is a valid-only re-evaluation.",
      {"level": 1})],
], size=17)
footer(s, 10)

import os
os.makedirs("slides", exist_ok=True)
out = "slides/ANLP_slides.pptx"
prs.save(out)
print("wrote", out)
